import QtQuick

QtObject {
    readonly property string activate: i18n("Activate")
    readonly property string saveTheme: i18n("Save Theme")
    readonly property string usageNetwork: i18n("Network Usage")
    readonly property string usageRam: i18n("Ram Usage")
    readonly property string network:  i18n("Network")
    readonly property string name: i18n("Name: ")
    readonly property string forceQuit: i18n("Force Quit")
    readonly property string quit: i18n("Quit")
    readonly property string cancel: i18n("Cancel")
    readonly property string pairDevice: i18n("Pair Device…")
    readonly property string bluetooth: i18n("Bluetooth")
    readonly property string browseFiles: i18n("Browse Files")
    readonly property string sendFile: i18n("Send File")
    readonly property string copy: i18n("Copy")
    readonly property string gridWidth: i18n("Grid width")
    readonly property string gridHeight: i18n("Grid Height")
    readonly property string downloadMissingAlbumCovers: i18n("Download missing album covers")
    readonly property string shadowOpacity: i18n("Shadow Opacity")
    readonly property string controlsColor: i18n("controls Color")
    readonly property string customColorWarning: i18n("It is not recommended to use Custom Color, in favor of the overall design")
    readonly property string customColor: i18n("Custom Color")
    readonly property string selectedGlobalThemes: i18n("Seleccted Global Theme's")
    readonly property string dark: i18n("Dark")
    readonly property string light: i18n("Light")
    readonly property string sensorNotListed: i18n("My sensor isn't listed")
    readonly property string systemIndicator: i18n("System indicator")
    readonly property string temperature: i18n("Temperature")
    readonly property string usagePercentage: i18n("Usage percentage")
    readonly property string save: i18n("Save")
    readonly property string volume: i18n("Volume")
    readonly property string brightness: i18n("Brightness")
    readonly property string dnd: i18n("DND")
    readonly property string battery: i18n("Battery")
    readonly property string screenshot: i18n("Screenshot")
    readonly property string edit: i18n("Edit Controls")
}


